added support for if tests etc and much more

diff --git a/tests/slack/roles/foo/scripts/preinstall b/tests/slack/roles/foo/scripts/preinstall
--- a/tests/slack/roles/foo/scripts/preinstall
+++ b/tests/slack/roles/foo/scripts/preinstall
@@ -15,3 +15,8 @@ apt install bar
 apt update
 apt-get update
  # hmm
+ssh_config=/tmp/dooby.txt
+echo "hello" >> $ssh_config
+if [[ $? -eq 0 ]]; then
+   echo "Either mycommand failed or <foo failed"
+fi
